# Generated by Django 3.2.7 on 2021-09-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(upload_to='images/')),
                ('name', models.CharField(help_text='A descriptive name', max_length=100)),
                ('street', models.CharField(help_text='Street', max_length=100)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State', max_length=100)),
                ('zip', models.IntegerField(help_text='Zipcode')),
            ],
        ),
    ]
